#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
11_figures_publication.py
Generate all publication-ready figures for the EII Bhutan PA analysis.

Figures:
- fig1_eii_map.png: Choropleth map of EII across PAs (generated by 09_maps_eii.py)
- fig2_pa_comparison.png: Bar chart comparing PA EII values
- fig3_components.png: Component maps (generated by 10_maps_components.py)
- fig4_method_sensitivity.png: Sensitivity analysis (optional)

Version History:
    1.0.0 - Initial implementation
"""

__version__ = "1.0.0"

import argparse
import sys
from pathlib import Path
from datetime import datetime

# Add parent directory for shared imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

from _shared.config import CONFIG, get_path
from _shared.logging_utils import setup_logger, log_session_info
from _shared.io_utils import ensure_dir, write_success_marker
from _shared.error_utils import (
    ErrorBundle, write_error_bundle, create_validation_report
)


# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_NAME = "11_figures_publication"
FIGURE_DPI = CONFIG["figure_dpi"]


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate publication-ready figures"
    )
    parser.add_argument(
        "--base-dir",
        type=str,
        default=None,
        help="Override base project directory"
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output files"
    )
    parser.add_argument(
        "--allow-pa-count-mismatch",
        action="store_true",
        help="Allow PA count different from expected 19"
    )
    parser.add_argument(
        "--enable-exports",
        action="store_true",
        help="Not used"
    )
    parser.add_argument(
        "--enable-method-compare",
        action="store_true",
        help="Generate sensitivity analysis figure"
    )
    parser.add_argument(
        "--allow-geometry-simplification",
        action="store_true",
        help="Not used"
    )
    return parser.parse_args()


def load_eii_stats(base_dir, logger):
    """Load EII statistics."""
    tables_dir = get_path("tables", base_dir)
    stats_path = tables_dir / "pa_eii_stats.csv"

    if not stats_path.exists():
        raise FileNotFoundError(f"EII stats not found: {stats_path}")

    return pd.read_csv(stats_path)


def load_component_stats(base_dir, logger):
    """Load component statistics."""
    tables_dir = get_path("tables", base_dir)
    stats_path = tables_dir / "pa_component_stats.csv"

    if not stats_path.exists():
        return None

    return pd.read_csv(stats_path)


def load_sensitivity_stats(base_dir, logger):
    """Load sensitivity analysis statistics (if available)."""
    tables_dir = get_path("tables", base_dir)
    stats_path = tables_dir / "pa_sensitivity_indices.csv"

    if not stats_path.exists():
        return None

    return pd.read_csv(stats_path)


def create_pa_comparison_figure(eii_df, output_path, logger):
    """
    Create bar chart comparing EII across PAs.

    Args:
        eii_df: EII statistics DataFrame
        output_path: Path to save figure
        logger: Logger instance
    """
    logger.info("Creating PA comparison figure...")

    # Sort by EII mean
    df_sorted = eii_df.sort_values('eii_mean', ascending=True).reset_index(drop=True)

    # Create figure
    fig, ax = plt.subplots(figsize=(10, 8))

    # Color by category
    categories = df_sorted['park'].unique()
    colors = plt.cm.Set2(np.linspace(0, 1, len(categories)))
    color_map = dict(zip(categories, colors))

    bars = ax.barh(
        range(len(df_sorted)),
        df_sorted['eii_mean'],
        xerr=df_sorted['eii_stdDev'],
        capsize=3,
        color=[color_map[c] for c in df_sorted['park']],
        edgecolor='black',
        linewidth=0.5,
        alpha=0.9,
        error_kw={'elinewidth': 1, 'alpha': 0.7}
    )

    # Labels
    ax.set_yticks(range(len(df_sorted)))
    ax.set_yticklabels(df_sorted['PA_name'], fontsize=9)

    ax.set_xlabel('Ecosystem Integrity Index (EII)', fontsize=11)
    ax.set_ylabel('Protected Area', fontsize=11)
    ax.set_title(
        'EII Comparison Across Bhutan Protected Areas',
        fontsize=13,
        fontweight='bold',
        pad=15
    )

    # Add legend for categories
    legend_patches = [
        mpatches.Patch(color=color_map[cat], label=cat)
        for cat in categories
    ]
    ax.legend(
        handles=legend_patches,
        title='PA Category',
        loc='lower right',
        fontsize=8,
        title_fontsize=9
    )

    # Add vertical line for network mean
    network_mean = eii_df['eii_mean'].mean()
    ax.axvline(
        network_mean,
        color='red',
        linestyle='--',
        linewidth=1.5,
        label=f'Network Mean: {network_mean:.3f}'
    )
    ax.annotate(
        f'Network Mean\n({network_mean:.3f})',
        xy=(network_mean, len(df_sorted) - 1),
        xytext=(network_mean + 0.02, len(df_sorted) - 2),
        fontsize=8,
        color='red'
    )

    # Grid
    ax.grid(axis='x', alpha=0.3)
    ax.set_axisbelow(True)

    # Set x-axis limits
    ax.set_xlim(0, min(1.0, df_sorted['eii_mean'].max() + 0.1))

    plt.tight_layout()

    # Save
    fig.savefig(output_path, dpi=FIGURE_DPI, bbox_inches='tight', facecolor='white')
    plt.close(fig)

    logger.info(f"Saved PA comparison figure: {output_path}")


def create_sensitivity_figure(eii_df, sensitivity_df, output_path, logger):
    """
    Create sensitivity analysis figure comparing different aggregation methods.

    Args:
        eii_df: Official EII statistics
        sensitivity_df: Sensitivity indices DataFrame
        output_path: Path to save figure
        logger: Logger instance
    """
    logger.info("Creating sensitivity analysis figure...")

    # Merge data
    merged = eii_df[['PA_name', 'eii_mean']].merge(
        sensitivity_df[['PA_name', 'sensitivity_min_mean', 'sensitivity_geom_mean_mean']],
        on='PA_name'
    )

    # Sort by official EII
    merged = merged.sort_values('eii_mean', ascending=False).reset_index(drop=True)

    # Create figure
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Panel A: Scatter plot comparison
    ax1 = axes[0]

    ax1.scatter(
        merged['eii_mean'],
        merged['sensitivity_min_mean'],
        alpha=0.7,
        s=60,
        c='blue',
        label='Minimum',
        marker='o'
    )
    ax1.scatter(
        merged['eii_mean'],
        merged['sensitivity_geom_mean_mean'],
        alpha=0.7,
        s=60,
        c='green',
        label='Geometric Mean',
        marker='^'
    )

    # 1:1 line
    lims = [0, max(merged['eii_mean'].max(), merged['sensitivity_min_mean'].max()) + 0.05]
    ax1.plot(lims, lims, 'k--', alpha=0.5, label='1:1 line')

    ax1.set_xlabel('Official EII (Precomputed)', fontsize=11)
    ax1.set_ylabel('Sensitivity Index', fontsize=11)
    ax1.set_title('A) EII vs Sensitivity Indices', fontsize=12, fontweight='bold')
    ax1.legend(loc='lower right')
    ax1.grid(alpha=0.3)

    # Panel B: Ranking comparison
    ax2 = axes[1]

    x = range(len(merged))
    width = 0.25

    ax2.bar(
        [i - width for i in x],
        merged['eii_mean'],
        width,
        label='Official EII',
        color='steelblue',
        alpha=0.8
    )
    ax2.bar(
        x,
        merged['sensitivity_min_mean'],
        width,
        label='Minimum',
        color='coral',
        alpha=0.8
    )
    ax2.bar(
        [i + width for i in x],
        merged['sensitivity_geom_mean_mean'],
        width,
        label='Geometric Mean',
        color='green',
        alpha=0.8
    )

    ax2.set_xticks(x)
    ax2.set_xticklabels(merged['PA_name'], rotation=45, ha='right', fontsize=7)
    ax2.set_ylabel('Index Value', fontsize=11)
    ax2.set_title('B) Comparison Across PAs', fontsize=12, fontweight='bold')
    ax2.legend(loc='upper right', fontsize=8)
    ax2.grid(axis='y', alpha=0.3)

    # Overall title
    fig.suptitle(
        'Sensitivity Analysis: EII vs Alternative Aggregation Methods\n'
        '(Note: Only official EII values should be used for reporting)',
        fontsize=12,
        fontweight='bold',
        y=1.02
    )

    plt.tight_layout()

    # Save
    fig.savefig(output_path, dpi=FIGURE_DPI, bbox_inches='tight', facecolor='white')
    plt.close(fig)

    logger.info(f"Saved sensitivity figure: {output_path}")


def main():
    args = parse_args()
    base_dir = args.base_dir

    # Set up logging
    log_dir = get_path("reproducibility", base_dir)
    ensure_dir(log_dir)
    log_file = log_dir / f"{SCRIPT_NAME}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    logger = setup_logger(SCRIPT_NAME, log_file)

    log_session_info(logger, SCRIPT_NAME, __version__, args)

    error_bundle = ErrorBundle(SCRIPT_NAME, __version__)
    error_bundle.add_context("base_dir", str(base_dir or get_path("base")))

    try:
        # Load data
        logger.info("Loading data...")
        eii_df = load_eii_stats(base_dir, logger)
        component_df = load_component_stats(base_dir, logger)

        # Validate PA count
        expected = CONFIG["expected_pa_count"]
        actual = len(eii_df)
        if actual != expected and not args.allow_pa_count_mismatch:
            raise ValueError(
                f"PA count mismatch: expected {expected}, found {actual}. "
                f"Use --allow-pa-count-mismatch to override."
            )

        # Output directory
        figures_dir = get_path("figures", base_dir)
        ensure_dir(figures_dir)

        outputs_created = []

        # Figure 2: PA Comparison
        fig2_path = figures_dir / "fig2_pa_comparison.png"
        if fig2_path.exists() and not args.overwrite:
            logger.info(f"Figure 2 exists, skipping: {fig2_path}")
        else:
            create_pa_comparison_figure(eii_df, fig2_path, logger)
            outputs_created.append(str(fig2_path))

        # Figure 4: Sensitivity (optional)
        if args.enable_method_compare:
            sensitivity_df = load_sensitivity_stats(base_dir, logger)
            if sensitivity_df is not None:
                fig4_path = figures_dir / "fig4_method_sensitivity.png"
                if fig4_path.exists() and not args.overwrite:
                    logger.info(f"Figure 4 exists, skipping: {fig4_path}")
                else:
                    create_sensitivity_figure(eii_df, sensitivity_df, fig4_path, logger)
                    outputs_created.append(str(fig4_path))
            else:
                logger.warning(
                    "Sensitivity analysis requested but pa_sensitivity_indices.csv not found. "
                    "Run 03_download_eii.py with --enable-method-compare first."
                )

        # Validation
        validation_dir = get_path("validation", base_dir)
        ensure_dir(validation_dir)

        checks = {
            "EII stats loaded": len(eii_df) > 0,
            "PA comparison figure created": (figures_dir / "fig2_pa_comparison.png").exists(),
        }

        report_path = create_validation_report(
            SCRIPT_NAME, __version__, checks, validation_dir
        )
        logger.info(f"Validation report: {report_path}")

        # Success marker
        script_dir = Path(__file__).parent
        success_path = write_success_marker(script_dir, SCRIPT_NAME)
        logger.info(f"Success marker: {success_path}")

        logger.info("\n" + "=" * 60)
        logger.info("PUBLICATION FIGURES COMPLETE")
        logger.info("=" * 60)
        logger.info(f"Figures created: {len(outputs_created)}")
        for f in outputs_created:
            logger.info(f"  - {f}")

    except Exception as e:
        logger.error(f"FATAL ERROR: {e}")
        error_bundle.capture_exception(e)
        error_dir = get_path("errors", base_dir)
        error_path = write_error_bundle(error_bundle, error_dir)
        logger.error(f"Error bundle written to: {error_path}")
        sys.exit(1)


if __name__ == "__main__":
    main()
